# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@2
#      - name: npm install and build webpack
#      - run: 

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-2016]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      
    - uses: actions/checkout@v2
    - name: Analysis
      uses: codacy/codacy-analysis-cli-action@master
      with:
        tool: ESLint
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        upload: true
      